//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToratEmet.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainFolder {
            get {
                return ((string)(this["MainFolder"]));
            }
            set {
                this["MainFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ToratEmetParentFolder {
            get {
                return ((string)(this["ToratEmetParentFolder"]));
            }
            set {
                this["ToratEmetParentFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultExternalFolder {
            get {
                return ((string)(this["DefaultExternalFolder"]));
            }
            set {
                this["DefaultExternalFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection OpenFileRecentSearches {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OpenFileRecentSearches"]));
            }
            set {
                this["OpenFileRecentSearches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenFileControlLastSearch {
            get {
                return ((string)(this["OpenFileControlLastSearch"]));
            }
            set {
                this["OpenFileControlLastSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double OpenFileWindowLeft {
            get {
                return ((double)(this["OpenFileWindowLeft"]));
            }
            set {
                this["OpenFileWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HtmlFontFamily {
            get {
                return ((string)(this["HtmlFontFamily"]));
            }
            set {
                this["HtmlFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int HtmlFontSize {
            get {
                return ((int)(this["HtmlFontSize"]));
            }
            set {
                this["HtmlFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentBooks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentBooks"]));
            }
            set {
                this["RecentBooks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ShemHashemDisplayOptions {
            get {
                return ((int)(this["ShemHashemDisplayOptions"]));
            }
            set {
                this["ShemHashemDisplayOptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SearchExplorerTabIndex {
            get {
                return ((int)(this["SearchExplorerTabIndex"]));
            }
            set {
                this["SearchExplorerTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentSearches {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentSearches"]));
            }
            set {
                this["RecentSearches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchAll {
            get {
                return ((bool)(this["SearchAll"]));
            }
            set {
                this["SearchAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CheckedTreeItems {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CheckedTreeItems"]));
            }
            set {
                this["CheckedTreeItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CheckedListBoxItems {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CheckedListBoxItems"]));
            }
            set {
                this["CheckedListBoxItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BusyIndexing {
            get {
                return ((bool)(this["BusyIndexing"]));
            }
            set {
                this["BusyIndexing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SearchMethodComboIndex {
            get {
                return ((int)(this["SearchMethodComboIndex"]));
            }
            set {
                this["SearchMethodComboIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SearchWindowLeft {
            get {
                return ((double)(this["SearchWindowLeft"]));
            }
            set {
                this["SearchWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseArmaicDictionary {
            get {
                return ((bool)(this["UseArmaicDictionary"]));
            }
            set {
                this["UseArmaicDictionary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FontSettingsTrigger {
            get {
                return ((string)(this["FontSettingsTrigger"]));
            }
            set {
                this["FontSettingsTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DockPosition {
            get {
                return ((string)(this["DockPosition"]));
            }
            set {
                this["DockPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResetShotcuts {
            get {
                return ((bool)(this["ResetShotcuts"]));
            }
            set {
                this["ResetShotcuts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdatesDisabled {
            get {
                return ((bool)(this["UpdatesDisabled"]));
            }
            set {
                this["UpdatesDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastSessionCollection {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastSessionCollection"]));
            }
            set {
                this["LastSessionCollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsOpenLastSessionEnabled {
            get {
                return ((bool)(this["IsOpenLastSessionEnabled"]));
            }
            set {
                this["IsOpenLastSessionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSessionSelectedTab {
            get {
                return ((string)(this["LastSessionSelectedTab"]));
            }
            set {
                this["LastSessionSelectedTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUpdateCheck {
            get {
                return ((string)(this["LastUpdateCheck"]));
            }
            set {
                this["LastUpdateCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fri, 12 Apr 2024 01:31:11 GMT")]
        public string UpdateFileInfo {
            get {
                return ((string)(this["UpdateFileInfo"]));
            }
            set {
                this["UpdateFileInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double DictionaryWindowLeft {
            get {
                return ((double)(this["DictionaryWindowLeft"]));
            }
            set {
                this["DictionaryWindowLeft"] = value;
            }
        }
    }
}
